/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_whitespace = 1,
  sym_comment = 2,
  anon_sym_PUBLIC = 3,
  anon_sym_PRIVATE = 4,
  anon_sym_INT = 5,
  anon_sym_STRING = 6,
  anon_sym_REAL = 7,
  anon_sym_QUALITY = 8,
  anon_sym_TIMESTAMP = 9,
  anon_sym_BOOL = 10,
  anon_sym_VOID = 11,
  sym_function_name = 12,
  anon_sym_FUNCTION = 13,
  sym_source_file = 14,
  sym__definition = 15,
  sym_function_scope = 16,
  sym__type = 17,
  sym_function_types = 18,
  sym_function_definition = 19,
  aux_sym_source_file_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_whitespace] = "whitespace",
  [sym_comment] = "comment",
  [anon_sym_PUBLIC] = "PUBLIC",
  [anon_sym_PRIVATE] = "PRIVATE",
  [anon_sym_INT] = "INT",
  [anon_sym_STRING] = "STRING",
  [anon_sym_REAL] = "REAL",
  [anon_sym_QUALITY] = "QUALITY",
  [anon_sym_TIMESTAMP] = "TIMESTAMP",
  [anon_sym_BOOL] = "BOOL",
  [anon_sym_VOID] = "VOID",
  [sym_function_name] = "function_name",
  [anon_sym_FUNCTION] = "FUNCTION",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_scope] = "function_scope",
  [sym__type] = "_type",
  [sym_function_types] = "function_types",
  [sym_function_definition] = "function_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_whitespace] = sym_whitespace,
  [sym_comment] = sym_comment,
  [anon_sym_PUBLIC] = anon_sym_PUBLIC,
  [anon_sym_PRIVATE] = anon_sym_PRIVATE,
  [anon_sym_INT] = anon_sym_INT,
  [anon_sym_STRING] = anon_sym_STRING,
  [anon_sym_REAL] = anon_sym_REAL,
  [anon_sym_QUALITY] = anon_sym_QUALITY,
  [anon_sym_TIMESTAMP] = anon_sym_TIMESTAMP,
  [anon_sym_BOOL] = anon_sym_BOOL,
  [anon_sym_VOID] = anon_sym_VOID,
  [sym_function_name] = sym_function_name,
  [anon_sym_FUNCTION] = anon_sym_FUNCTION,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_scope] = sym_function_scope,
  [sym__type] = sym__type,
  [sym_function_types] = sym_function_types,
  [sym_function_definition] = sym_function_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PUBLIC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PRIVATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STRING] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QUALITY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TIMESTAMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BOOL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VOID] = {
    .visible = true,
    .named = false,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_FUNCTION] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_function_types] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\r', 55,
        '!', 57,
        '/', 2,
        'B', 36,
        'F', 50,
        'I', 34,
        'P', 40,
        'Q', 49,
        'R', 16,
        'S', 43,
        'T', 18,
        'V', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(54);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(55);
      if (lookahead == '!') ADVANCE(57);
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'B') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'C') ADVANCE(58);
      END_STATE();
    case 12:
      if (lookahead == 'C') ADVANCE(48);
      END_STATE();
    case 13:
      if (lookahead == 'D') ADVANCE(66);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(59);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'G') ADVANCE(61);
      END_STATE();
    case 18:
      if (lookahead == 'I') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'I') ADVANCE(51);
      END_STATE();
    case 20:
      if (lookahead == 'I') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'I') ADVANCE(11);
      END_STATE();
    case 22:
      if (lookahead == 'I') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(45);
      END_STATE();
    case 25:
      if (lookahead == 'L') ADVANCE(65);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 'L') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'M') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'M') ADVANCE(14);
      END_STATE();
    case 31:
      if (lookahead == 'N') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 'N') ADVANCE(17);
      END_STATE();
    case 33:
      if (lookahead == 'N') ADVANCE(68);
      END_STATE();
    case 34:
      if (lookahead == 'N') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'O') ADVANCE(25);
      END_STATE();
    case 36:
      if (lookahead == 'O') ADVANCE(35);
      END_STATE();
    case 37:
      if (lookahead == 'O') ADVANCE(20);
      END_STATE();
    case 38:
      if (lookahead == 'O') ADVANCE(33);
      END_STATE();
    case 39:
      if (lookahead == 'P') ADVANCE(64);
      END_STATE();
    case 40:
      if (lookahead == 'R') ADVANCE(19);
      if (lookahead == 'U') ADVANCE(10);
      END_STATE();
    case 41:
      if (lookahead == 'R') ADVANCE(22);
      END_STATE();
    case 42:
      if (lookahead == 'S') ADVANCE(47);
      END_STATE();
    case 43:
      if (lookahead == 'T') ADVANCE(41);
      END_STATE();
    case 44:
      if (lookahead == 'T') ADVANCE(60);
      END_STATE();
    case 45:
      if (lookahead == 'T') ADVANCE(52);
      END_STATE();
    case 46:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 47:
      if (lookahead == 'T') ADVANCE(6);
      END_STATE();
    case 48:
      if (lookahead == 'T') ADVANCE(23);
      END_STATE();
    case 49:
      if (lookahead == 'U') ADVANCE(9);
      END_STATE();
    case 50:
      if (lookahead == 'U') ADVANCE(31);
      END_STATE();
    case 51:
      if (lookahead == 'V') ADVANCE(8);
      END_STATE();
    case 52:
      if (lookahead == 'Y') ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_whitespace);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\r') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PUBLIC);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PRIVATE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_INT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_STRING);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_REAL);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_QUALITY);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_TIMESTAMP);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_BOOL);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_VOID);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_function_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_FUNCTION);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(1),
    [anon_sym_PRIVATE] = ACTIONS(1),
    [anon_sym_INT] = ACTIONS(1),
    [anon_sym_STRING] = ACTIONS(1),
    [anon_sym_REAL] = ACTIONS(1),
    [anon_sym_QUALITY] = ACTIONS(1),
    [anon_sym_TIMESTAMP] = ACTIONS(1),
    [anon_sym_BOOL] = ACTIONS(1),
    [anon_sym_VOID] = ACTIONS(1),
    [anon_sym_FUNCTION] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(11),
    [sym__definition] = STATE(2),
    [sym_function_scope] = STATE(7),
    [sym__type] = STATE(9),
    [sym_function_types] = STATE(12),
    [sym_function_definition] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(9),
    [anon_sym_PRIVATE] = ACTIONS(9),
    [anon_sym_INT] = ACTIONS(11),
    [anon_sym_STRING] = ACTIONS(11),
    [anon_sym_REAL] = ACTIONS(11),
    [anon_sym_QUALITY] = ACTIONS(11),
    [anon_sym_TIMESTAMP] = ACTIONS(11),
    [anon_sym_BOOL] = ACTIONS(11),
    [anon_sym_VOID] = ACTIONS(11),
    [anon_sym_FUNCTION] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym_function_scope] = STATE(7),
    [sym__type] = STATE(9),
    [sym_function_types] = STATE(12),
    [sym_function_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(9),
    [anon_sym_PRIVATE] = ACTIONS(9),
    [anon_sym_INT] = ACTIONS(11),
    [anon_sym_STRING] = ACTIONS(11),
    [anon_sym_REAL] = ACTIONS(11),
    [anon_sym_QUALITY] = ACTIONS(11),
    [anon_sym_TIMESTAMP] = ACTIONS(11),
    [anon_sym_BOOL] = ACTIONS(11),
    [anon_sym_VOID] = ACTIONS(11),
    [anon_sym_FUNCTION] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(3),
    [sym_function_scope] = STATE(7),
    [sym__type] = STATE(9),
    [sym_function_types] = STATE(12),
    [sym_function_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(19),
    [anon_sym_PRIVATE] = ACTIONS(19),
    [anon_sym_INT] = ACTIONS(22),
    [anon_sym_STRING] = ACTIONS(22),
    [anon_sym_REAL] = ACTIONS(22),
    [anon_sym_QUALITY] = ACTIONS(22),
    [anon_sym_TIMESTAMP] = ACTIONS(22),
    [anon_sym_BOOL] = ACTIONS(22),
    [anon_sym_VOID] = ACTIONS(22),
    [anon_sym_FUNCTION] = ACTIONS(25),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(28),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(30),
    [anon_sym_PRIVATE] = ACTIONS(30),
    [anon_sym_INT] = ACTIONS(30),
    [anon_sym_STRING] = ACTIONS(30),
    [anon_sym_REAL] = ACTIONS(30),
    [anon_sym_QUALITY] = ACTIONS(30),
    [anon_sym_TIMESTAMP] = ACTIONS(30),
    [anon_sym_BOOL] = ACTIONS(30),
    [anon_sym_VOID] = ACTIONS(30),
    [anon_sym_FUNCTION] = ACTIONS(30),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(32),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(34),
    [anon_sym_PRIVATE] = ACTIONS(34),
    [anon_sym_INT] = ACTIONS(34),
    [anon_sym_STRING] = ACTIONS(34),
    [anon_sym_REAL] = ACTIONS(34),
    [anon_sym_QUALITY] = ACTIONS(34),
    [anon_sym_TIMESTAMP] = ACTIONS(34),
    [anon_sym_BOOL] = ACTIONS(34),
    [anon_sym_VOID] = ACTIONS(34),
    [anon_sym_FUNCTION] = ACTIONS(34),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(36),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_PUBLIC] = ACTIONS(38),
    [anon_sym_PRIVATE] = ACTIONS(38),
    [anon_sym_INT] = ACTIONS(38),
    [anon_sym_STRING] = ACTIONS(38),
    [anon_sym_REAL] = ACTIONS(38),
    [anon_sym_QUALITY] = ACTIONS(38),
    [anon_sym_TIMESTAMP] = ACTIONS(38),
    [anon_sym_BOOL] = ACTIONS(38),
    [anon_sym_VOID] = ACTIONS(38),
    [anon_sym_FUNCTION] = ACTIONS(38),
  },
  [STATE(7)] = {
    [sym__type] = STATE(9),
    [sym_function_types] = STATE(14),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_INT] = ACTIONS(11),
    [anon_sym_STRING] = ACTIONS(11),
    [anon_sym_REAL] = ACTIONS(11),
    [anon_sym_QUALITY] = ACTIONS(11),
    [anon_sym_TIMESTAMP] = ACTIONS(11),
    [anon_sym_BOOL] = ACTIONS(11),
    [anon_sym_VOID] = ACTIONS(11),
    [anon_sym_FUNCTION] = ACTIONS(40),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(42), 8,
      anon_sym_INT,
      anon_sym_STRING,
      anon_sym_REAL,
      anon_sym_QUALITY,
      anon_sym_TIMESTAMP,
      anon_sym_BOOL,
      anon_sym_VOID,
      anon_sym_FUNCTION,
  [17] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_FUNCTION,
  [27] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_function_name,
  [37] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
  [47] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_FUNCTION,
  [57] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_function_name,
  [67] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_FUNCTION,
  [77] = 3,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(54), 1,
      sym_function_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 17,
  [SMALL_STATE(10)] = 27,
  [SMALL_STATE(11)] = 37,
  [SMALL_STATE(12)] = 47,
  [SMALL_STATE(13)] = 57,
  [SMALL_STATE(14)] = 67,
  [SMALL_STATE(15)] = 77,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_scope, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_types, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [48] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cicode(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cicode",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
